modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "creaturesundiscovered"
version = "${version}"
displayName = "Creatures Undiscovered"
authors = "JoostMSoftware"
description = '''
A mob add-on for the Regions Unexplored mod!
'''
#logoFile = ""

[[dependencies.creaturesundiscovered]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creaturesundiscovered]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creaturesundiscovered]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"